### ISSUE TITLE
Trying to use ScalaJs 1.0.0

### ISSUE THREAD

**Issue by FabioPinheiro** [oyvindberg/ScalablyTypedDemos#21]
I'm trying to use ScalablyTyped for the first time and was unable to use it with scala 1.0.0.

I'm doing anything wrong. Does anyone have an idea of how can I investigate the problem?
Any help would be appreciated. Thanks in advance!

I updated the file `project/plugins.sbt` to:
```
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.0.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.16.0")

resolvers += Resolver.bintrayRepo("oyvindberg", "converter")
addSbtPlugin("org.scalablytyped.converter" % "sbt-converter" % "1.0.0-beta4")
```

and when running any demo `three/start` I get:
```
sbt:demos> three/start 
[info] Updating NPM dependencies
[info] Using lockfile /home/fabio/workspace/Demos/three/yarn.lock
[info] yarn install v1.15.2
[info] [1/4] Resolving packages...
[info] [2/4] Fetching packages...
[info] info fsevents@1.2.9: The platform "linux" is incompatible with this module.
[info] info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[info] [3/4] Linking dependencies...
[info] [4/4] Building fresh packages...
[info] Done in 4.04s.
[error] stack trace is suppressed; run last three / Compile / stImport for the full output
[error] (three / Compile / stImport) java.lang.NoSuchMethodError: 'java.lang.String org.scalajs.sbtplugin.ScalaJSCrossVersion$.currentBinaryVersion()'
[error] Total time: 5 s, completed Feb 16, 2020, 11:44:35 PM


sbt:demos> last three/Compile/stImport
[error] java.lang.NoSuchMethodError: 'java.lang.String org.scalajs.sbtplugin.ScalaJSCrossVersion$.currentBinaryVersion()'
[error]         at org.scalablytyped.converter.plugin.ScalablyTypedConverterPlugin$.$anonfun$stScalaJsBundlerIntegration$6(ScalablyTypedConverterPlugin.scala:100)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (three / Compile / stImport) java.lang.NoSuchMethodError: 'java.lang.String org.scalajs.sbtplugin.ScalaJSCrossVersion$.currentBinaryVersion()'
```

**Comment by mcallisto** [comment]
Unfortunately Slinky has not been updated (yet) to ScalaJs 1.x.
It should happen quite soon with the next release, see https://github.com/shadaj/slinky/pull/321.

**Comment by mcallisto** [comment]
@FabioPinheiro sorry, we are not in the Slinky "flavour" demos, so what I wrote does not apply here.

**Comment by FabioPinheiro** [comment]
The error seems to point to this line of code: 
https://github.com/ScalablyTyped/Converter/blob/e994542cd7cb40b71e5ab59d83be5cd1ab9bbcfc/sbt-converter06/src/main/scala/org/scalablytyped/converter/plugin/ScalablyTypedConverterPlugin.scala#L100

So what is the difference between sbt plugin `sbt-converter` and `sbt-converter06` ?

**Comment by FabioPinheiro** [comment]
This will not work for ScalaJs 1.0.0 after @gzm0  changed 
https://github.com/scala-js/scala-js/commit/61e7bfa25eb4296d5ac3ec1e5bd1889479be1e63

I will try to fix this after work and do a PR

**Comment by gzm0** [comment]
As a stop-gap solution, you can use `org.scalajs.ir.ScalaJSVersions.binaryCross`. Note that this is an unstable API and can break in minor Scala.js releases.

If you want a stable API (and I think that is a fair request), please file a [feature request][1] to Scala.js.

[1]: https://github.com/scala-js/scala-js/issues

**Comment by oyvindberg** [comment]
Released a new version of the plugin now with full support for Scala.js 1. The [SlinkyDemos](https://github.com/ScalablyTyped/SlinkyDemos) repo has been upgraded, while this will be on 0.6 probably until scalajs-react is updated.
